baseurl = "http://pgbr.postgresql.org.br/2017/"
title = "#PGBR17"
languageCode = "en-us"
contentdir = "app/content"
datadir = "app/data"
layoutdir = "app/layouts"
publishdir = "dist"
staticdir = "app/static"
themesdir = "app/themes"
canonifyurls = false

[params]
  description = "ConferÃªncia Brasileira de PostgreSQL"
  author = "Nikola Tesla"